# Generated by Django 3.1 on 2020-09-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200912_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Done'), (2, 'In Progress'), (3, 'To Do')], default=1),
            preserve_default=False,
        ),
    ]
